apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .Release.Name }}-root-password
spec:
  vaultAuthRef: {{ required ".Values.vaultAuthRef is required" .Values.vaultAuthRef }}
  refreshAfter: 30s

  type: kv-v2
  mount: {{ required ".Values.vaultSecretMount is required" .Values.vaultSecretMount }}
  path: {{ required ".Values.vaultSecretPath is required" .Values.vaultSecretPath }}

  destination:
    name: {{ .Release.Name }}-root-password
    create: true

  rolloutRestartTargets:
    - kind: StatefulSet
      name: {{ .Release.Name }}-master
    - kind: StatefulSet
      name: {{ .Release.Name }}-slave
    - kind: StatefulSet
      name: {{ .Release.Name }}-arbiter

