apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
spec:
  ports:
    - port: {{ required ".Values.port" .Values.port }}
      targetPort: {{ .Values.containerPort }}
  selector:
    release: {{ include "name" . }}
