apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
    - port: {{ required ".Values.port" .Values.port }}
      targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ .Release.Name }}
