{{ if .Values.vaultAuthRef }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .Release.Name }}-env
spec:
  vaultAuthRef: {{ .Values.vaultAuthRef }}
  refreshAfter: 30s

  type: kv-v2
  mount: {{ required ".Values.vaultSecretMount is required" .Values.vaultSecretMount }}
  path: {{ required ".Values.vaultSecretPath is required" .Values.vaultSecretPath }}

  destination:
    name: {{ .Release.Name }}-env
    create: true

  rolloutRestartTargets:
    - kind: Deployment
      name: {{ .Release.Name }}
{{ end }}
